Admin menu
Ezehkiel/STI_PRO1 pull request #15
Opened 2019-10-03 09:38 UTC by zereddiamond

Add admin menu for list, add, update or delete users. Database updated : add at the beginning of the script creation `PRAGMA journal_mode = WAL;` to enable WAL ( Write Ahead Logging) for read and write conccurency. I do not push the new version of database.

2019-10-03 10:16 UTC, Ezehkiel requested changes
On peut discuter en live si tu veux

2019-10-03 10:16 UTC, Ezehkiel commented on site/html/addUser.php
> +        ?>
- Je pense que c'est mieux de mettre le code php en haut et à la place de faire un echo tu mets ta string dans une variable et ici tu fais juste un if il y a qqch dans la variable tu l'echo
- De plus je suis pas sur mais il se passe quoi si on ne rentre pas de pseudo et de password ? J'ai pas l'impression que tu check s'il y a qqch dans les variables

2019-10-03 10:16 UTC, Ezehkiel commented on site/html/addUser.php
> +    <form method="post" action="">
Pas besoin de mettre le action si il est vide

2019-10-03 10:16 UTC, Ezehkiel commented on site/html/modifyUser.php
> +            echo '<p><button type="submit" name="update_user_form" class="btn btn-primary">Modify user</button></p>';
Pour ça tu peux fermer les balises php et faire en HTML

2019-10-03 10:16 UTC, Ezehkiel commented on site/html/modifyUser.php
> +            //print_r($user_info);
A enlever

2019-10-03 10:16 UTC, Ezehkiel commented on site/html/addUser.php
> +        <p><label>Password : </label><input type="password" name="passwordNewUser" /></p>
Faire un autre champs pour confirmer le password

2019-10-03 10:16 UTC, Ezehkiel commented on site/html/admin.php
> +                    }
Je comprends pas ce `if`, il fait que ça affiche pas les actions pour l'utilisateur actuel ?

2019-10-03 10:16 UTC, Ezehkiel commented on site/html/deleteUser.php
> +?>
- Je pense qu'il faut faire un truc genre "Etes vous sur de vouloir supprimer cet utilisateur" ? Soit avec une modal comme c'etait fait avant soit faire ça sur cette page. 
- Est-ce que tu as regarder si en supprimant un utilisateur ça supprime aussi ses messages ?

2019-10-03 10:16 UTC, Ezehkiel commented on site/html/info_user.php
> +?>
ça c'était un fichier a moi qui n'a pas été utilisé. Tu peux le supprimer

2019-10-03 10:16 UTC, Ezehkiel commented on site/html/modifyUser.php
> +    error_reporting(E_ALL);
Ca afficher les erreurs ça ? Et si oui où  Et est-ce que c'est encore utilie ?

2019-10-03 13:12 UTC, zereddiamond commented on site/html/admin.php
> +                    }
Oui exactement, pour éviter de se modifier nous-même

2019-10-04 07:54 UTC, Ezehkiel approved these changes

2019-10-04 08:50 UTC, merged